version: "3.9"

networks:
  kafka-cluster:
    driver: bridge

services:
  document-store:
    extends:
      file: ./docker-compose-boot.yaml
      service: _spring-boot
    build:
      args:
        PROJECT: document-store

  document-upload:
    extends:
      file: ./docker-compose-boot.yaml
      service: _spring-boot
    build:
      args:
        PROJECT: document-upload

