version: '3.9'

networks:
  kafka-cluster:
    driver: bridge

services:
  ui:
    build:
      dockerfile: kafdrop.Dockerfile
    restart: "no"
    hostname: kafdrop
    container_name: kafdrop
    depends_on:
      - broker
      - schema-registry
    ports:
        - '9000:9000'
    expose:
      - '9000'
    networks:
        - kafka-cluster
    environment:
      WAIT_HOSTS: "broker:29092, schema-registry:8081"
      WAIT_TIMEOUT: 120
      WAIT_SLEEP_INTERVAL: 2
      KAFKA_BROKERCONNECT: "broker:29092"
      SCHEMAREGISTRY_CONNECT: "http://schema-registry:8081"